name: Weekly Music Recommendation

on:
  schedule:
    # Runs at 12:00 UTC on Monday
    - cron: '5 4 * * 1,5'
  workflow_dispatch:  # Allows manual triggering

jobs:
  post-recommendation:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run script
      env:
        SPOTIFY_CLIENT_ID: ${{ secrets.SPOTIFY_CLIENT_ID }}
        SPOTIFY_CLIENT_SECRET: ${{ secrets.SPOTIFY_CLIENT_SECRET }}
        SPOTIFY_PLAYLIST: "https://open.spotify.com/playlist/2yYeWkP6mwREwWyW8Igrrn?si=64dc43f36091422b"
        BLUESKY_USERNAME: ${{ secrets.BLUESKY_USERNAME }}
        BLUESKY_PASSWORD: ${{ secrets.BLUESKY_PASSWORD }}
      run: python run.py 